<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Destination;
use App\Models\District;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        // ── Kabupaten/Kota di Kalimantan Timur ───────────────────────
        $districts = [
            'Kota Balikpapan' => 'Kalimantan Timur',
            'Kota Samarinda' => 'Kalimantan Timur',
            'Kota Bontang' => 'Kalimantan Timur',
            'Kabupaten Kutai Kartanegara' => 'Kalimantan Timur',
            'Kabupaten Berau' => 'Kalimantan Timur',
            'Kabupaten Penajam Paser Utara' => 'Kalimantan Timur',
        ];

        $districtIds = [];
        foreach ($districts as $name => $province) {
            $district = District::firstOrCreate(['name' => $name, 'province' => $province]);
            $districtIds[$name] = $district->id;
        }

        $categoryIds = Category::pluck('id', 'name');

        // ── Data destinasi Kalimantan Timur ─────────────────────────
        $destinations = [
            // ═══════════ AKSES DARAT ═══════════
            [
                'name' => 'Pantai Melawai',
                'category' => 'Pantai',
                'district' => 'Kota Balikpapan',
                'latitude' => -1.2762,
                'longitude' => 116.8156,
                'description' => 'Pantai di tengah Kota Balikpapan, spot favorit warga lokal menikmati sunset sambil kuliner malam di pinggir pantai.',
                'address' => 'Jl. Jenderal Sudirman, Balikpapan, Kalimantan Timur',
                'price_range' => 'Gratis',
                'facilities' => ['Warung kuliner malam', 'Area duduk santai', 'Toilet umum', 'Parkir'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800',
                'rating' => 4.4,
                'review_count' => 87,
                'is_featured' => true,
                'access_type' => 'darat',
            ],
            [
                'name' => 'Pantai Manggar Segarasari',
                'category' => 'Pantai',
                'district' => 'Kota Balikpapan',
                'latitude' => -1.1949,
                'longitude' => 116.9391,
                'description' => 'Pantai berpasir putih di Balikpapan Timur, populer untuk rekreasi keluarga, ATV, dan olahraga pantai.',
                'address' => 'Manggar, Balikpapan Timur, Kalimantan Timur',
                'price_range' => 'Rp 5.000 - Rp 15.000',
                'facilities' => ['Penyewaan ATV', 'Gazebo', 'Toilet umum', 'Warung makan', 'Area parkir'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
                'rating' => 4.3,
                'review_count' => 62,
                'is_featured' => false,
                'access_type' => 'darat',
            ],
            [
                'name' => 'Hutan Lindung Sungai Wain',
                'category' => 'Budaya & Sejarah',
                'district' => 'Kota Balikpapan',
                'latitude' => -1.0284,
                'longitude' => 116.8058,
                'description' => 'Hutan konservasi tropis yang jadi habitat orangutan liar dan beruang madu, cocok untuk trekking edukasi alam.',
                'address' => 'Karang Joang, Balikpapan Utara, Kalimantan Timur',
                'price_range' => 'Rp 25.000 - Rp 50.000',
                'facilities' => ['Pemandu trekking', 'Pusat edukasi satwa', 'Jalur trekking', 'Toilet umum'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
                'rating' => 4.6,
                'review_count' => 54,
                'is_featured' => false,
                'access_type' => 'darat',
            ],
            [
                'name' => 'Bukit Bangkirai',
                'category' => 'Gunung',
                'district' => 'Kabupaten Kutai Kartanegara',
                'latitude' => -1.1167,
                'longitude' => 116.9333,
                'description' => 'Hutan hujan tropis dengan jembatan tajuk (canopy bridge) setinggi 30 meter menghubungkan pohon-pohon raksasa berusia ratusan tahun.',
                'address' => 'Kecamatan Samboja, Kutai Kartanegara, Kalimantan Timur',
                'price_range' => 'Rp 35.000 - Rp 60.000',
                'facilities' => ['Canopy bridge', 'Penginapan cottage', 'Jalur trekking', 'Pemandu lokal'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1516214104703-d870798883c5?w=800',
                'rating' => 4.7,
                'review_count' => 71,
                'is_featured' => true,
                'access_type' => 'darat',
            ],
            [
                'name' => 'Pulau Kumala',
                'category' => 'Taman & Hutan',
                'district' => 'Kabupaten Kutai Kartanegara',
                'latitude' => -0.3833,
                'longitude' => 117.1333,
                'description' => 'Taman rekreasi keluarga di delta Sungai Mahakam, Tenggarong, dengan kereta gantung dan wahana bermain.',
                'address' => 'Tenggarong, Kutai Kartanegara, Kalimantan Timur',
                'price_range' => 'Rp 10.000 - Rp 40.000',
                'facilities' => ['Kereta gantung (cable car)', 'Wahana bermain anak', 'Area foto', 'Warung makan'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800',
                'rating' => 4.2,
                'review_count' => 48,
                'is_featured' => false,
                'access_type' => 'darat',
            ],
            [
                'name' => 'Museum Mulawarman',
                'category' => 'Budaya & Sejarah',
                'district' => 'Kabupaten Kutai Kartanegara',
                'latitude' => -0.4262,
                'longitude' => 117.1264,
                'description' => 'Bekas keraton Kesultanan Kutai Kartanegara, menyimpan koleksi singgasana, perhiasan kerajaan, dan artefak sejarah Kutai.',
                'address' => 'Jl. Diponegoro, Tenggarong, Kutai Kartanegara, Kalimantan Timur',
                'price_range' => 'Rp 5.000 - Rp 10.000',
                'facilities' => ['Pemandu museum', 'Area parkir', 'Toilet umum'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?w=800',
                'rating' => 4.5,
                'review_count' => 39,
                'is_featured' => false,
                'access_type' => 'darat',
            ],
            [
                'name' => 'Masjid Islamic Center Samarinda',
                'category' => 'Budaya & Sejarah',
                'district' => 'Kota Samarinda',
                'latitude' => -0.4870,
                'longitude' => 117.1450,
                'description' => 'Masjid termegah di Kalimantan Timur, terletak di tepi Sungai Mahakam, salah satu masjid terbesar di Asia Tenggara.',
                'address' => 'Jl. Slamet Riyadi, Samarinda, Kalimantan Timur',
                'price_range' => 'Gratis',
                'facilities' => ['Menara pandang', 'Area foto', 'Perpustakaan', 'Parkir luas'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1564769625392-651b2c319b9c?w=800',
                'rating' => 4.8,
                'review_count' => 112,
                'is_featured' => true,
                'access_type' => 'darat',
            ],
            [
                'name' => 'Air Terjun Tanah Merah',
                'category' => 'Air Terjun',
                'district' => 'Kota Samarinda',
                'latitude' => -0.4547,
                'longitude' => 117.0142,
                'description' => 'Air terjun bertingkat yang sejuk di pinggiran Samarinda, cocok untuk piknik dan bermain air keluarga.',
                'address' => 'Tanah Merah, Samarinda Utara, Kalimantan Timur',
                'price_range' => 'Rp 10.000 - Rp 20.000',
                'facilities' => ['Area piknik', 'Kolam alami', 'Warung', 'Parkir'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800',
                'rating' => 4.3,
                'review_count' => 45,
                'is_featured' => false,
                'access_type' => 'darat',
            ],
            [
                'name' => 'Bontang Kuala',
                'category' => 'Budaya & Sejarah',
                'district' => 'Kota Bontang',
                'latitude' => 0.1250,
                'longitude' => 117.5000,
                'description' => 'Perkampungan nelayan di atas laut dengan rumah panggung kayu ulin dan jembatan kayu sepanjang 2,5 km, ikon wisata Bontang.',
                'address' => 'Bontang Kuala, Bontang Utara, Kalimantan Timur',
                'price_range' => 'Gratis',
                'facilities' => ['Jembatan kayu', 'Warung seafood', 'Spot foto', 'Dermaga nelayan'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1580418827493-f2b22c0a76cb?w=800',
                'rating' => 4.5,
                'review_count' => 58,
                'is_featured' => false,
                'access_type' => 'darat',
            ],

            // ═══════════ AKSES KAPAL (Kepulauan Derawan, Berau) ═══════════
            [
                'name' => 'Pulau Derawan',
                'category' => 'Pantai',
                'district' => 'Kabupaten Berau',
                'latitude' => 2.2864,
                'longitude' => 118.2447,
                'description' => 'Surga bawah laut Kalimantan Timur — air laut jernih kehijauan, penyu hijau berenang bebas di sekitar dermaga, spot diving/snorkeling kelas dunia.',
                'address' => 'Pulau Derawan, Kecamatan Derawan, Kabupaten Berau, Kalimantan Timur',
                'price_range' => 'Rp 500.000 - Rp 1.500.000 (paket 2 hari 1 malam)',
                'facilities' => ['Penginapan tepi pantai', 'Penyewaan alat snorkeling & diving', 'Warung makan', 'Dermaga kayu'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=800',
                'rating' => 4.9,
                'review_count' => 203,
                'is_featured' => true,
                'access_type' => 'kapal',
                'departure_port' => 'Pelabuhan Tanjung Batu, Berau',
                'crossing_duration_minutes' => 45,
                'crossing_cost_estimate' => 150000,
                'crossing_notes' => 'Dari Bandara Kalimarau (Berau/Tanjung Redeb), lanjut darat ±2 jam ke Tanjung Batu, lalu speedboat carter/reguler ±45 menit ke Pulau Derawan. Speedboat carter lebih fleksibel jadwal, harga carter per kapal (isi 8-10 orang) sekitar Rp 800.000 - Rp 1.200.000 pulang-pergi.',
            ],
            [
                'name' => 'Pulau Maratua',
                'category' => 'Pantai',
                'district' => 'Kabupaten Berau',
                'latitude' => 2.2500,
                'longitude' => 118.6167,
                'description' => 'Pulau atol terbesar di Indonesia, rumah bagi resort-resort eksklusif dan spot diving Kakaban Wall serta pertemuan hiu martil.',
                'address' => 'Pulau Maratua, Kecamatan Maratua, Kabupaten Berau, Kalimantan Timur',
                'price_range' => 'Rp 800.000 - Rp 3.000.000 (paket menginap)',
                'facilities' => ['Resort & homestay', 'Dive center', 'Dermaga', 'Warung lokal'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
                'rating' => 4.8,
                'review_count' => 96,
                'is_featured' => true,
                'access_type' => 'kapal',
                'departure_port' => 'Pelabuhan Tanjung Batu, Berau (atau langsung dari Pulau Derawan)',
                'crossing_duration_minutes' => 90,
                'crossing_cost_estimate' => 350000,
                'crossing_notes' => 'Speedboat dari Tanjung Batu langsung ke Maratua ±1,5 jam, atau dari Pulau Derawan lanjut speedboat ±45 menit lagi. Cuaca & gelombang laut sangat memengaruhi jadwal — sebaiknya berangkat pagi hari dan cek kondisi laut ke operator kapal H-1.',
            ],
            [
                'name' => 'Danau Ubur-ubur Kakaban',
                'category' => 'Budaya & Sejarah',
                'district' => 'Kabupaten Berau',
                'latitude' => 2.1500,
                'longitude' => 118.5333,
                'description' => 'Danau purba di tengah Pulau Kakaban, salah satu dari hanya 2 tempat di dunia yang punya ubur-ubur tanpa sengat — bisa berenang bersama ribuan ubur-ubur dengan aman.',
                'address' => 'Pulau Kakaban, Kecamatan Maratua, Kabupaten Berau, Kalimantan Timur',
                'price_range' => 'Rp 50.000 (tiket masuk) + biaya kapal',
                'facilities' => ['Jalur trekking kayu', 'Area ganti pakaian', 'Dermaga'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800',
                'rating' => 4.9,
                'review_count' => 84,
                'is_featured' => true,
                'access_type' => 'kapal',
                'departure_port' => 'Pulau Derawan (via speedboat tur gugusan pulau)',
                'crossing_duration_minutes' => 40,
                'crossing_cost_estimate' => 200000,
                'crossing_notes' => 'Umumnya dikunjungi sebagai bagian dari paket island-hopping dari Derawan (Kakaban - Maratua - Sangalaki dalam 1 hari). Wajib pakai pelampung, dilarang memakai sunscreen/lotion sebelum berenang di danau untuk menjaga ekosistem ubur-uburnya.',
            ],
            [
                'name' => 'Pulau Sangalaki',
                'category' => 'Pantai',
                'district' => 'Kabupaten Berau',
                'latitude' => 2.0833,
                'longitude' => 118.4167,
                'description' => 'Pulau konservasi penyu terbesar di Kalimantan Timur, spot terbaik melihat pari manta di alam liar.',
                'address' => 'Pulau Sangalaki, Kecamatan Maratua, Kabupaten Berau, Kalimantan Timur',
                'price_range' => 'Rp 100.000 (tiket masuk) + biaya kapal',
                'facilities' => ['Pusat konservasi penyu', 'Spot foto', 'Area istirahat'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1546026423-cc4642628d2b?w=800',
                'rating' => 4.7,
                'review_count' => 41,
                'is_featured' => false,
                'access_type' => 'kapal',
                'departure_port' => 'Pulau Derawan (via speedboat tur gugusan pulau)',
                'crossing_duration_minutes' => 35,
                'crossing_cost_estimate' => 200000,
                'crossing_notes' => 'Sama seperti Kakaban, biasanya jadi bagian paket island-hopping dari Derawan. Waktu terbaik lihat pari manta pagi hari (06.00-09.00).',
            ],

            // ═══════════ PENYEBERANGAN FERI (Balikpapan ↔ PPU) ═══════════
            [
                'name' => 'Pantai Nipah-nipah',
                'category' => 'Pantai',
                'district' => 'Kabupaten Penajam Paser Utara',
                'latitude' => -1.2500,
                'longitude' => 116.7500,
                'description' => 'Pantai tenang di Penajam Paser Utara, dekat area calon Ibu Kota Nusantara (IKN), pas untuk healing sambil susur perairan Teluk Balikpapan.',
                'address' => 'Nipah-nipah, Penajam, Penajam Paser Utara, Kalimantan Timur',
                'price_range' => 'Rp 5.000 - Rp 10.000',
                'facilities' => ['Warung makan', 'Gazebo', 'Toilet umum', 'Area parkir'],
                'cover_image_url' => 'https://images.unsplash.com/photo-1519852162463-a7773ffd7dae?w=800',
                'rating' => 4.1,
                'review_count' => 27,
                'is_featured' => false,
                'access_type' => 'kapal',
                'departure_port' => 'Pelabuhan Feri Kariangau, Balikpapan',
                'crossing_duration_minutes' => 30,
                'crossing_cost_estimate' => 25000,
                'crossing_notes' => 'Feri roro reguler dari Pelabuhan Kariangau (Balikpapan) ke Pelabuhan Penajam beroperasi hampir 24 jam dengan jadwal cukup sering (setiap 30-60 menit). Bisa bawa motor/mobil. Setiba di Penajam, lanjut darat ±20 menit ke pantai.',
            ],
        ];

        foreach ($destinations as $item) {
            $categoryId = $categoryIds[$item['category']] ?? null;
            $districtId = $districtIds[$item['district']] ?? null;

            Destination::firstOrCreate(
                ['slug' => Str::slug($item['name'])],
                [
                    'name' => $item['name'],
                    'description' => $item['description'],
                    'category_id' => $categoryId,
                    'district_id' => $districtId,
                    'latitude' => $item['latitude'],
                    'longitude' => $item['longitude'],
                    'address' => $item['address'],
                    'price_range' => $item['price_range'],
                    'facilities' => $item['facilities'],
                    'cover_image_url' => $item['cover_image_url'],
                    'gallery_urls' => [$item['cover_image_url']],
                    'rating' => $item['rating'],
                    'review_count' => $item['review_count'],
                    'is_featured' => $item['is_featured'],
                    'access_type' => $item['access_type'],
                    'departure_port' => $item['departure_port'] ?? null,
                    'crossing_duration_minutes' => $item['crossing_duration_minutes'] ?? null,
                    'crossing_cost_estimate' => $item['crossing_cost_estimate'] ?? null,
                    'crossing_notes' => $item['crossing_notes'] ?? null,
                ]
            );
        }
    }
}